#!/bin/sh

#assuming disk is already partitioned
timedatectl set-ntp true

umount -a
mount /dev/sda2 /mnt
rm -rf /mnt/*
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
mkdir /mnt/{Data,home}
mount /dev/sda3 /mnt/home
mount /dev/sdb1 /mnt/Data
pacman -Sy
pacstrap /mnt base linux-zen linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
